In [72]:
## Basic Python Data Structures and Numpy

#The objective of this assignment is to introduce Jupyter notebook as a development environment and to introduce data structures in Python that provide the basis for much of the data manipulation and, eventually, visualization work that we will perform in later sections.

#**Recall the keyboard shortcuts introduced in the video lectures:**
#- Convert current chunk to Markown: *Esc* -> *M*
#- New code chunk...
#    - above current cell: *Esc* -> *A*
#    - below current cell: *Esc* -> *B*
#- Run code chunk: *Shift+Enter*
#- Comment: *ctrl + /* (PC) or *command + /* (Mac)

### Task 1: Create and Modify a List
We first begin with one of the simplest ways to store data: a list. Recall that when we were working in R, lists could store data of different types (characters, integers, logicals) and they could retain that data type when referenced.

Fortunately, Python offers some similar functionality. We will start by exploring some of the basic features of a list

*1a) Creating a list*

Create a list using square brackets

In [73]:
# Create a list
my_list = ['c',1,3,True] # Add some elements (characters, integers, logicals) to this list, separated by a comma

*1b) Appending a list and selecting the last item*

Use *.append()* to an element to the end of that list, then reference it using [-1]. 

In [74]:
my_list.append(2.43)
my_list[-1]

2.43

### Task 2: Subsetting a list
*2a:* Select the first element of that list.

**Question**: How is this different from R?

In [75]:
my_list[0]
#the python coding is different from R. In Python the subset starts with 0, in R it starts with 1

'c'

*2b:* Select the last element of that list

In [76]:
my_list[-1]
#we can use -1 to refer to the last element of the list

2.43

### Task 3: Modifying elements of a list and list comprehension
*3a:* Try creating another list of just numbers (e.g. [1, 3, 4]) and then try adding 1 to every element of that list (even if it contains a string). What happens?

In [77]:
 list_2 = [1,3,4]
 list_2 + 1
#got an error of TypeError: can only concatenate list (not "int") to list

TypeError: can only concatenate list (not "int") to list

*3b*: We can try this again using list comprehension. Starting with the following code as a base, complete the previous task; add 1 to each element of list_2.

In [78]:
# Every element of the list x
# x is used to just reference each specific element in this list
[str(x) + ' BOO' for x in list_2] # we could also do [item for item in list2]
new_list_2 = [x + 1 for x in list_2]
new_list_2

[2, 4, 5]

## Numpy: A comparison to R
Once you start working with numpy, you will begin to realize that many of its functions and objects bear a striking resemblence to those used in R. 

We can begin by considering the atomic vector in R. Recall that in R this is just a single data type (e.g. character, integer, float). Numpy Vectors in Python work the same way! We will illustrate this by first creating a numpy array. 

In [79]:
# !! Don't forget to import numpy!!
import numpy as np

### Task 4: Creating numpy array
Using the list you used in task 3, you can create a numpy array with the following code. What happens when you add a character to that original list and try converting it to a numpy array? How does this compare to R?

In [80]:
list_2.append('c')
list_2
my_array = np.array(list_2)
my_array
# this works the same as in python
# If you try to combine different data types into an array in R, R will coerce the elements to a single data type, 
# following logical to integer to double to character sequence array(['1', '3', '4', 'c'], dtype='<U11')
# If you try to combine different data types into an array in Python, Python will upcast the elements
# in this case all the integers are converted to charater array(['1', '3', '4', 'c'], dtype='<U11')

array(['1', '3', '4', 'c'], dtype='<U11')

As with R, there are several built-in functions within numpy that can help us create arrays and matrices. Here we have listed just a few:

    - np.arange()
    - np.linspace()
    - np.random.randn()
    - np.random.randint()
    - np.random.random()

*4b*: We will use np.random.randn() to create a vector and convert it to a 10x10 matrix. Modify the code to create a 20 x 5 matrix

In [81]:
my_matrix = np.random.randn(100).reshape(20, 5)

### Task 5: Subsetting and summarizing a numpy array


As with R, we can subset matrices (2d arrays) using the syntax:

         my_matrix[row_subset, col_subset]
         
*row_subset* and/or *col_subset* can be logical arrays or arrays of integers designating the rows/columns we would like to keep. Crucially, if we do not want to subset by row or column, you must include a colon. For example, if we are only filtering by columns (not rows) we would write:

        my_matrix[:, col_subset]

*5a*: Filter the matrix created in 4b to include only columns 2 and 3.

In [82]:
my_matrix[:,[2,3]]

array([[-0.99536535, -0.00700605],
       [-0.27149244, -1.81149968],
       [ 0.72208716,  0.44250478],
       [-0.22783287,  0.89308314],
       [-0.59383159,  0.44316774],
       [-1.11829405,  1.69683975],
       [-0.43975708, -0.1996581 ],
       [-0.59561755,  0.04514049],
       [ 0.0073486 ,  0.01151778],
       [-0.14967021,  1.66575071],
       [ 0.23947712,  2.3721353 ],
       [ 2.14738517, -0.96017581],
       [-0.07081416, -0.05868315],
       [ 1.00507089, -0.17670935],
       [ 0.86261446,  0.00672388],
       [-2.1161981 ,  0.33602972],
       [-1.23279631,  0.97345451],
       [-1.0064129 , -0.57688204],
       [-0.64574146,  0.95681008],
       [-0.52435628, -0.72782881]])

*5b*: Recall the distinction between functions and methods. For each of the following lines of code, create a comment describing its function, then rewrite it using a method instead of the function.

In [83]:
np.ravel(my_matrix)
# np.ravel(a, order='C')
# Return a contiguous flattened array.
# A 1-D array, containing the elements of the input, is returned.  A copy is made only if needed.
# order : {'C','F', 'A', 'K'}, optional

# Use the ravel method on the array object
flat_array = my_matrix.ravel()
print(flat_array)
# the difference between function and method are:
# function is not class/object based
# method is class/object based
# since my_matrix is an object, when we call it directly on it, we call the ravel method, the ravel method is binded on the object


[ 0.94558533  0.11473025 -0.99536535 -0.00700605  0.84251474  0.39095819
 -0.49148095 -0.27149244 -1.81149968 -0.17828981 -0.6845612   0.33045493
  0.72208716  0.44250478 -1.99060453 -0.36133919  0.88477684 -0.22783287
  0.89308314  1.36377811  1.10681234 -0.07139228 -0.59383159  0.44316774
 -0.30296355 -0.62838951  0.1356999  -1.11829405  1.69683975 -0.41235855
  0.75248407 -0.29033951 -0.43975708 -0.1996581   0.63486611  0.42424387
  0.14917919 -0.59561755  0.04514049  0.37516209 -3.10087971 -0.98279587
  0.0073486   0.01151778  1.70720504 -0.63198164  0.43242489 -0.14967021
  1.66575071 -1.01939282  0.40626756 -1.14204846  0.23947712  2.3721353
 -0.45282703  0.77665511 -0.64481853  2.14738517 -0.96017581  0.78575018
  0.31014544  0.9899869  -0.07081416 -0.05868315 -0.5133485   1.46628162
 -0.96262388  1.00507089 -0.17670935  0.25134631 -0.05039215  0.9331794
  0.86261446  0.00672388  0.62440487  0.83441592 -0.42460315 -2.1161981
  0.33602972 -0.16108596 -0.73168172 -0.17349322 -1.23

In [84]:
np.argsort(my_matrix, axis = 1)
# np.argsort(a, axis=-1, kind=None, order=None)
# Returns the indices that would sort an array.
# Perform an indirect sort along the given axis using the algorithm specified
# by the `kind` keyword. It returns an array of indices of the same shape as
# `a` that index data along the given axis in sorted order.
# axis=1, it sorts the indices within each row.
my_matrix.argsort(axis=1)
# again, we call the argsort method directly on the matrix object

array([[2, 3, 1, 4, 0],
       [3, 1, 2, 4, 0],
       [4, 0, 1, 3, 2],
       [0, 2, 1, 3, 4],
       [2, 4, 1, 3, 0],
       [2, 0, 4, 1, 3],
       [2, 1, 3, 4, 0],
       [2, 3, 1, 4, 0],
       [0, 1, 2, 3, 4],
       [4, 0, 2, 1, 3],
       [1, 4, 2, 0, 3],
       [3, 1, 0, 4, 2],
       [4, 2, 3, 0, 1],
       [1, 3, 4, 2, 0],
       [0, 3, 4, 2, 1],
       [2, 1, 4, 3, 0],
       [4, 2, 0, 1, 3],
       [2, 3, 4, 1, 0],
       [1, 2, 0, 3, 4],
       [0, 3, 1, 2, 4]], dtype=int64)

In [85]:
np.cumsum(my_matrix, axis = 0)
#np.cumsum(a, axis=None, dtype=None, out=None)
#Return the cumulative sum of the elements along a given axis.
#axis=0 will compute the cumulative sum for each column, summing down the rows
#the second row will be the sum of first row+its original row values
#the third row will be the sum of second row+its original row values
my_matrix.cumsum(axis = 0)
# again, we call the cumsum method directly on the matrix object

array([[ 0.94558533,  0.11473025, -0.99536535, -0.00700605,  0.84251474],
       [ 1.33654352, -0.37675069, -1.26685779, -1.81850573,  0.66422493],
       [ 0.65198232, -0.04629576, -0.54477063, -1.37600095, -1.3263796 ],
       [ 0.29064313,  0.83848107, -0.7726035 , -0.48291781,  0.03739851],
       [ 1.39745547,  0.76708879, -1.36643509, -0.03975007, -0.26556503],
       [ 0.76906597,  0.90278869, -2.48472914,  1.65708968, -0.67792358],
       [ 1.52155003,  0.61244918, -2.92448622,  1.45743158, -0.04305748],
       [ 1.9457939 ,  0.76162838, -3.52010377,  1.50257207,  0.33210461],
       [-1.15508581, -0.22116749, -3.51275517,  1.51408985,  2.03930966],
       [-1.78706745,  0.21125739, -3.66242538,  3.17984056,  1.01991684],
       [-1.38079989, -0.93079107, -3.42294826,  5.55197586,  0.56708981],
       [-0.60414478, -1.5756096 , -1.27556308,  4.59180004,  1.35283998],
       [-0.29399934, -0.5856227 , -1.34637724,  4.5331169 ,  0.83949148],
       [ 1.17228228, -1.54824657, -0.3